set_property IOSTANDARD LVCMOS33 [get_ports alarm_led]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports key_to_active]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property DRIVE 12 [get_ports alarm_led]

set_property IOSTANDARD LVCMOS33 [get_ports {sw_on_board[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_on_board[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_on_board[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw_on_board[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {display[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {display[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ena]
set_property PACKAGE_PIN H2 [get_ports {display[7]}]
set_property PACKAGE_PIN D2 [get_ports {display[6]}]
set_property PACKAGE_PIN E2 [get_ports {display[5]}]
set_property PACKAGE_PIN F3 [get_ports {display[4]}]
set_property PACKAGE_PIN F4 [get_ports {display[3]}]
set_property PACKAGE_PIN D3 [get_ports {display[2]}]
set_property PACKAGE_PIN E3 [get_ports {display[1]}]
set_property PACKAGE_PIN D4 [get_ports {display[0]}]
set_property PACKAGE_PIN K2 [get_ports alarm_led]
set_property PACKAGE_PIN P17 [get_ports clk]
set_property PACKAGE_PIN G6 [get_ports ena]
set_property PACKAGE_PIN R11 [get_ports key_to_active]
set_property PACKAGE_PIN R17 [get_ports rst]
set_property PACKAGE_PIN R2 [get_ports {sw_on_board[3]}]
set_property PACKAGE_PIN M4 [get_ports {sw_on_board[2]}]
set_property PACKAGE_PIN N4 [get_ports {sw_on_board[1]}]
set_property PACKAGE_PIN R1 [get_ports {sw_on_board[0]}]
